# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-jira" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "64945d75a3486185aea8464f34a12e2f02bb240dd3fc080d89b3b29064d38321"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfa140d15c0e8b173dfe0b29e25751e02a96baa88c562d5f0b732444628aa866"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74afa13f50ea34858e35d47401dace8a414117a4fd1008b76f53c2c75a99d175"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88ee8aad2c214f81ae4cb9f4c521f13b5eac2ceafce042b7e6f44b89115e314e"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-jira"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-jira"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-jira"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-jira has been installed.

    To configure, run:
      atk-jira init

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
