# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-jira" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "1ec1d7ca957b18d28e8e59f8e0010d107cb4b81ccdab5bb34f5309c2c534c83a"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ebedf2b1813774427f1a94af0d205c38ec3bc967da9a6c81bad87f00608b519"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b52b5cf5c4dc0560ae7123ddb852452c00a3554ef5c90a2a81ed6c160993ce4f"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fdf9a3a46e821063e4f37b0d6b73f856a8ef8d4caa46e8c813d4718f7f2228c"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-jira"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-jira"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-jira"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-jira has been installed.

    To configure, run:
      atk-jira init

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
