# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-cfl" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "ab7b73c6c6483c98aa63d0857296985b002e0893839535bceff3e771b3107f97"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "368df02e7c2c22236a4264a061a9c1ed7f959757455cc7409833373a80371362"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "876f906f101e4f0b0d4893d7d55a1906d4104595ea6d98fee2c40fae6811803c"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d434650096dfee061b5f99386e5ecd4eda7f6fc3ce591a1ef077a76103548f9"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-cfl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-cfl"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-cfl has been installed. Run 'atk-cfl init' to configure.
  EOS
end
