# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-cfl" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "1cad3c2d69b4a1361b2bca6349aeb74353da04445c8b1c6a48b0936fa3279df3"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce6df0d7f530ac30692374a8ef856d3d429ce946fc63edd07c9231f88bc8a2dd"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0cf85ffe8025742e63bb5fcbd5617f3fc6724b536e333bb9e5ec237dc6086425"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e43b284fb1c74871745ed1d383cb55b49aba98c143a80828a384cd899ad998b"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-cfl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-cfl"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-cfl has been installed. Run 'atk-cfl init' to configure.
  EOS
end
