# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-jira" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ed1c21c218fe220c0e037b0fa26cc218f8827e6f96eccbd8c21e0f9059bac947"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db46c5bab6816b7f674bae0a577913a26a8b44867de1a1051f328247a4472aad"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99847b51bff6ac680550623126e4ac24bfe9376544db1ad015896940884d6eda"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bad710020f639827bdfa5b5a774276c75ea1672edcba26b392c74e019196024a"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-jira_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-jira"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-jira"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-jira"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-jira has been installed.

    To configure, run:
      atk-jira init

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
