# This file was generated by GoReleaser. DO NOT EDIT.
cask "atk-cfl" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "3bed01b0e8017d7301b0d0fc8b3be18efa2e701810e7d816383a93dea530ff81"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d050ea6897b78b5eb4b4e29bc74afdd007ac7294452db9f4d02066e191300790"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fa83994c67355c46d45c9005b39ef569296f7f1e4453c03ccf1ba12db941ed6"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "287c4c15096808e2e62fe3a5a28b9fd2ac6c832ee527262794caa34fb9966a59"
      url "https://github.com/wohsj110/atlassian_cli/releases/download/v#{version}/atk-cfl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atk-cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/wohsj110/atlassian_cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atk-cfl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atk-cfl"]
  end

  # No zap stanza required

  caveats <<~EOS
    atk-cfl has been installed. Run 'atk-cfl init' to configure.
  EOS
end
